apiVersion: v1
kind: Service
metadata:
  name: {{ include "helloworld.fullname" . }}
  labels:
{{ include "helloworld.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "helloworld.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
